---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - curl
      - gpg
      - debian-archive-keyring
      - apt-transport-https
    update_cache: true
    force_apt_get: true

- name: Add gpg key
  ansible.builtin.apt_key:
    url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
    state: present

- name: Add source to lists
  ansible.builtin.apt_repository:
    repo: "deb https://packages.gitlab.com/runner/gitlab-runner/debian/ {{ ansible_distribution_release }} main"
    filename: gitlab-runner

- name: Add source repository to lists
  ansible.builtin.apt_repository:
    repo: "deb-src https://packages.gitlab.com/runner/gitlab-runner/debian/ {{ ansible_distribution_release }} main"
    filename: gitlab-runner

- name: Setup apt pinning
  ansible.builtin.template:
    src: apt-gitlab-runner.pref.j2
    dest: /etc/apt/preferences.d/pin-gitlab-runner.pref
    owner: root
    group: root
    mode: '0644'

- name: Install gitlab runner
  ansible.builtin.apt:
    name: gitlab-runner
    update_cache: true
    force_apt_get: true

- name: Add cleanup script
  ansible.builtin.template:
    src: gitlab-runner-cleanup.sh.j2
    dest: /usr/local/bin/gitlab-runner-cleanup.sh
    owner: root
    group: root
    mode: "0755"

- name: Add cronjob for cleanup
  ansible.builtin.cron:
    name: "gitlab runner cleanup"
    state: present
    minute: "0"
    hour: "0"
    user: root
    job: "/usr/local/bin/gitlab-runner-cleanup.sh"
